name = "hammer-demo"
version = "0.1.0"
defaultTargets = ["HammerDemo"]

[moreServerOptions]
# 10-second timeout for Zipperposition and Duper, respectively
# (This is just for demoing setting timeouts)
auto.tptp.timeout = 10
duper.maxSaturationTime = 10

[[require]]
name = "Hammer"
scope = "JOSHCLUNE"
# rev = "v4.22.0"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.22.0"

[[lean_lib]]
name = "HammerDemo"
