name = "hammer-demo"
version = "0.1.0"
defaultTargets = ["HammerDemo"]

[moreServerOptions]
# 10-second timeout for Zipperposition and Duper, respectively
auto.tptp.timeout = 10
duper.maxSaturationTime = 10

[[require]]
name = "Hammer"
git = "https://github.com/JOSHCLUNE/LeanHammer"
rev = "37d8051b857d42ee16f1bf237bba0a2046813365"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.20.0-rc5"

[[lean_lib]]
name = "HammerDemo"
